[cmd_duration]
min_time = 0

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[kubernetes]
format = 'on [â˜¸ï¸c $context](green) '
disabled = false

[gcloud]
format = "[$symbol$active]($style) "
style = "bold yellow"

[status]
style = "red"
symbol = "ğŸ’£ "
format = '[\[$symbol $status\]]($style) '
disabled = false
